function mod = model_function_with_diff_optim(xtrain,ytrain,hidden,epochs) 
%trainFcn = 'trainlm'; 
trainFcn='trainrp'; 
hiddenLayerSize = hidden; 
net = patternnet(hiddenLayerSize, trainFcn); 
net=configure(net,xtrain,ytrain); 
net.trainParam.epochs=epochs; 
%[net,tr] = train(net,xtrain,ytrain); 
mod=net;nd